Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/dsc10-notes-5yRYveSa-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/dsc10-notes-5yRYveSa-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/dsc10-notes-5yRYveSa-py3.10/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.cache/pypoetry/virtualenvs/dsc10-notes-5yRYveSa-py3.10/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/dsc10-notes-5yRYveSa-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/dsc10-notes-5yRYveSa-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/dsc10-notes-5yRYveSa-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
decade_from_year(1987)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [7], line 1[0m
[0;32m----> 1[0m [43mdecade_from_year[49m([38;5;241m1987[39m)

[0;31mNameError[0m: name 'decade_from_year' is not defined
NameError: name 'decade_from_year' is not defined

